trigger:
- none

pool:
  name: UKS-DHCW-NWRI-DEV-ADOSelfHostPool

steps:

- script: echo "Hello, world!"
  displayName: 'Print Hello World'

- script: |
    echo "OS info:"
    cat /etc/os-release
    echo "apt-get location:"
    ls -l /usr/bin/apt-get || echo "not found"
    echo "PATH:"
    echo $PATH
  displayName: 'Verify environment'

- script: |
    which nc
    nc -h
  displayName: 'Verify netcat'
  
- script: echo "Testing ADO connectivity to all NWRI resources"
  displayName: 'Start connectivity tests'

- script: nc -zv uks-dhcw-dev-nwri-appconfig.azconfig.io 443
  displayName: 'Testing ADO connection to Application Configuration store'

- script: nc -zv uksdhcwdevnwriacr.azurecr.io 443
  displayName: 'Testing ADO connection to Azure Container Registry'

- script: nc -zv uks-dhcw-dev-nwri-kv.vault.azure.net 443
  displayName: 'Testing ADO connection to Azure Key Vault'

- script: nc -zv uksmydevnwriapp.internal.yellowtree-fadb23ed.uksouth.azurecontainerapps.io 443
  displayName: 'Testing ADO connection to NWRI Container App'

- script: nc -zv uksdhcwdevnwrisa.blob.core.windows.net 443
  displayName: 'Testing ADO connection to NWRI Storage Account'
   
- script: terraform --version
  displayName: 'Check Terraform version'
   
- task: AzureCLI@2
  displayName: 'Deploy Hello World to Container Apps'
  inputs:
    azureSubscription: 'Azure - NHSWales-DHCW-NWRI-Subscription'   
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      set -e

      # Variables
      RG="UKSouth-DHCW-APP-DEV-NWRI-RG"
      APP_NAME="nwri-hello-world-app"
      ENV_NAME="uks-dhcw-dev-nwri-cae"
      LOCATION="uksouth"
      ACR_NAME="uksdhcwdevnwriacr"
      IMAGE_NAME="containerapps-helloworld:latest"
      SOURCE_IMAGE="mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"

      echo "Checking if repository exists..."

      REPO_EXISTS=$(az acr repository show \
        --name $ACR_NAME \
        --repository ${IMAGE_NAME%:*} \
        --output none 2>/dev/null && echo "true" || echo "false")

      if [ "$REPO_EXISTS" == "true" ]; then
        echo "Repository exists, checking tags..."

        EXISTS=$(az acr repository show-tags \
          --name $ACR_NAME \
          --repository ${IMAGE_NAME%:*} \
          --query "contains(@, '${IMAGE_NAME#*:}')" \
          -o tsv)

        if [ "$EXISTS" == "true" ]; then
          echo "Image $IMAGE_NAME exists → deleting..."
          az acr repository delete \
            --name $ACR_NAME \
            --repository ${IMAGE_NAME%:*} \
            --yes
        else
          echo "Tag does not exist → nothing to delete"
        fi
      else
        echo "Repository does not exist → skipping delete"
      fi
      
      az account set --subscription 7bda6ea8-f947-4efa-930c-c4c3f9c56d48
      
      az acr list -o table
      
      echo "Importing image into ACR..."
      az acr import \
        --name $ACR_NAME \
        --source $SOURCE_IMAGE \
        --image $IMAGE_NAME

      echo "Checking if Container App exists..."
      if az containerapp show --name $APP_NAME --resource-group $RG > /dev/null 2>&1; then
        echo "App exists → updating image..."
        az containerapp update \
          --name $APP_NAME \
          --resource-group $RG \
          --image "$ACR_NAME.azurecr.io/$IMAGE_NAME"
      else
        echo "App does not exist → creating..."
        az containerapp create \
          --name $APP_NAME \
          --resource-group $RG \
          --environment $ENV_NAME \
          --image "$ACR_NAME.azurecr.io/$IMAGE_NAME" \
          --target-port 80 \
          --ingress internal
      fi

      echo "Fetching app URL..."
      FQDN=$(az containerapp show \
        --name $APP_NAME \
        --resource-group $RG \
        --query properties.configuration.ingress.fqdn \
        -o tsv)

      echo "======================================"
      echo " Container App deployed successfully!"
      echo " URL: https://$FQDN"
      echo "======================================"

# Wait for Container App readiness
- task: AzureCLI@2
  displayName: "Wait for Container App readiness"
  inputs:
    azureSubscription: 'Azure - NHSWales-DHCW-NWRI-Subscription'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      APP_NAME="nwri-hello-world-app"
      RG="UKSouth-DHCW-APP-DEV-NWRI-RG"

      echo "Waiting for container app to become ready..."
      for i in {1..10}; do
        STATUS=$(az containerapp show \
          --name $APP_NAME \
          --resource-group $RG \
          --query "properties.latestRevisionHealthState" -o tsv)
        echo "Current status: $STATUS"
        if [ "$STATUS" = "Healthy" ]; then
          echo "App is ready"
          break
        fi
        sleep 10
      done

# Test internal endpoint
- script: |
    echo "Calling internal endpoint..."
    curl -v http://nwri-hello-world-app.internal.yellowtree-fadb23ed.uksouth.azurecontainerapps.io/
  displayName: "Curl internal Container App endpoint"