trigger:
  none

pool:
  name: UKS-DHCW-NWRI-DEV-ADOSelfHostPool

variables:
  containerAppName: nwri-test-app001
  resourceGroup: UKSouth-DHCW-APP-DEV-NWRI-RG
  acrName: uksdhcwdevnwriacr
  acrLoginServer: uksdhcwdevnwriacr.azurecr.io
  uamiResourceId: /subscriptions/7bda6ea8-f947-4efa-930c-c4c3f9c56d48/resourceGroups/UKSouth-DHCW-APP-DEV-NWRI-RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/uks-dhcw-dev-nwri-umi

steps:

# Deploy container app
- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'Azure - NHSWales-DHCW-NWRI-Subscription'
    acrName: '$(acrName)'
    imageToDeploy: '$(acrLoginServer)/containerapps-helloworld:latest'
    containerAppName: '$(containerAppName)'
    resourceGroup: '$(resourceGroup)'
    containerAppEnvironment: 'uks-dhcw-dev-nwri-cae'
    targetPort: '80'
    ingress: 'internal'

# Wait for Container App readiness
- task: AzureCLI@2
  displayName: "Wait for Container App readiness"
  inputs:
    azureSubscription: 'Azure - NHSWales-DHCW-NWRI-Subscription'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Waiting for container app to become ready..."
      for i in {1..30}; do
        STATUS=$(az containerapp show \
          -n $(containerAppName) \
          -g $(resourceGroup) \
          --query "properties.latestRevisionHealthState" -o tsv)
        echo "Current status: $STATUS"
        if [ "$STATUS" = "Healthy" ]; then
          echo "App is ready"
          break
        fi
        sleep 10
      done

# Test internal endpoint
- script: |
    echo "Calling internal endpoint..."
    curl -v http://$(containerAppName).internal.yellowtree-fadb23ed.uksouth.azurecontainerapps.io/
  displayName: "Curl internal Container App endpoint"
