#trigger:
#- none

trigger:
  branches:
    include:
    - 5743

#pr:
#  branches:
#    include:
#    - branchA

pool:
  name: NWRI-ADO-POOL

steps:
- script: |
    echo "OS info:"
    cat /etc/os-release
    echo "apt-get location:"
    ls -l /usr/bin/apt-get || echo "not found"
    echo "PATH:"
    echo $PATH
  displayName: 'Verify environment'
  
- script: |
    timeout 5 bash -c "</dev/tcp/uks-dhcw-dev-nwri-appconfig.azconfig.io/443" \
    && echo "Application Config: SUCCESS" || echo "Application Config: FAILED"

    timeout 5 bash -c "</dev/tcp/uksdhcwdevnwriacr.azurecr.io/443" \
    && echo "ACR: SUCCESS" || echo "ACR: FAILED"

    timeout 5 bash -c "</dev/tcp/uks-dhcw-dev-nwri-kv.vault.azure.net/443" \
    && echo "Key Vault: SUCCESS" || echo "Key Vault: FAILED"

    timeout 5 bash -c "</dev/tcp/uksmydevnwriapp.internal.yellowtree-fadb23ed.uksouth.azurecontainerapps.io/443" \
    && echo "Container App: SUCCESS" || echo "Container App: FAILED"

    timeout 5 bash -c "</dev/tcp/uksdhcwdevnwrisa.blob.core.windows.net/443" \
    && echo "Storage: SUCCESS" || echo "Storage: FAILED"
  displayName: 'Connectivity tests (no nc required)'
   
