trigger: none

pool:
  name: UKS-DHCW-NWRI-DEV-ADOSelfHostPool

steps:

- powershell: Write-Host "Hello, world!"
  displayName: 'Print Hello World'

- powershell: |
    if (Get-Command Test-NetConnection -ErrorAction SilentlyContinue) {
        Write-Host "Test-NetConnection is available"
    } else {
        Write-Host "Test-NetConnection not found"
    }
  displayName: 'Verify network tools'

- powershell: |
    Write-Host "Checking dotnet version..."
    dotnet --version
    Write-Host "Installed SDKs:"
    dotnet --list-sdks
    Write-Host "Installed runtimes:"
    dotnet --list-runtimes
  displayName: 'Check dotnet SDK and runtimes'

- powershell: docker --version
  displayName: 'Checking docker version'

- powershell: docker ps
  displayName: 'docker ps'

- powershell: docker info
  displayName: 'Checking docker info'

- powershell: |
    Write-Host "Checking Azure CLI version..."
    az --version
  displayName: 'Check Azure CLI version'

- powershell: Write-Host "Testing ADO connectivity to all NWRI resources"
  displayName: 'Start connectivity tests'

- powershell: Test-NetConnection -ComputerName "uks-dhcw-dev-nwri-appconfig.azconfig.io" -Port 443
  displayName: 'Testing ADO connection to Application Configuration store'

- powershell: Test-NetConnection -ComputerName "uksdhcwdevnwriacr.azurecr.io" -Port 443
  displayName: 'Testing ADO connection to Azure Container Registry'

- powershell: Test-NetConnection -ComputerName "uks-dhcw-dev-nwri-kv.vault.azure.net" -Port 443
  displayName: 'Testing ADO connection to Azure Key Vault'

- powershell: Test-NetConnection -ComputerName "uksdhcwdevnwrisa.blob.core.windows.net" -Port 443
  displayName: 'Testing ADO connection to NWRI Storage Account'