<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NWRI.eReferralsService.API</RootNamespace>
    <UserSecretsId>cafebabe-dead-beef-face-feed12345</UserSecretsId>

    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Hl7.Fhir.R4" Version="6.1.1" />
    <PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="6.1.1" />
    <PackageReference Include="Firely.Fhir.Packages" Version="5.0.2" />
    <PackageReference Include="Firely.Fhir.Validation.R4" Version="3.1.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.5.0" />
    <PackageReference Include="JsonSchema.Net" Version="9.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="[10.1.7]" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="[2.23.0,3.0)" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="FhirPackages/**/*.tgz">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Schemas/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\README.md">
      <Link>README.md</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Resources/Fhir/*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
